create database customer_behavior;
use customer_behavior;
select * from customers;
-- What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue
from customers
group by 1;

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customers
where discount_applied="yes" and purchase_amount>= (select avg(purchase_amount) from customers);

-- Which are the top 5 products with the highest average review ratings?

select item_purchased,round(avg(review_rating),2) as "Average Product Rating"
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amount between Standard and Express Shipping
select shipping_type,round(avg(purchase_amount),2) as Average_Purchase_Amount from customers
where shipping_type in ("Express" ,"Standard")
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers

select subscription_status, count(customer_id) as Total_Customers,sum(purchase_amount) as Total_revenue,round(avg(purchase_amount),2) as Average_Spend
from customers
group by 1
order by Total_revenue,Average_Spend;

-- Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased ,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*)*100,2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into New, Returning , and Loyal based on their total number of previous purchases ,and show the count of each segment.
select 
case when previous_purchases=1 then "New"
     when previous_purchases between 2 and 10 then "Returning"
     else "Loyal"
end as Customer_Segment ,count(*) as "No of Customers" from customers
group by 1;

-- What are the top 3 most purchased products within each category.
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased
)

select item_rank, category,item_purchased,total_orders
 from item_counts
 where item_rank<=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) from customers
where  previous_purchases>5
group by subscription_status;

-- What is the revenue contributuion of each group?
select age_group,sum(purchase_amount) as revenue
from customers
group by 1
order by 2 desc;





